//
//  TestHelper.swift
//  Envisionary
//
//  Created by Campbell McGavin on 3/26/23.
//

import SwiftUI

struct TestHelper {
    
//    let dreamNames =
//    [
//        "Become a millionaire",
//        "Own a zoo",
//        "Get married and have a beautiful family",
//        "Learn 5 langauges",
//        "Have a summer home",
//        "Travel to all 7 continents",
//        "Hike mount everest",
//
//    ]
    let habitNames =
    [
        "Be physically active every day",
        "Eat plenty of vegetables and some fruit every day",
        "Get enough sleep and eat breakfast",
        "Switch to low-fat (1% or less) milk, cheese, and yogurt",
        "Do something healthy every day that makes you feel good",
        "Drink water instead of soda or juice",
        "Turn off the screens and live your life",
        "Snack on healthy foods",
        "Eat smaller amounts",
        "Eat less fast food",
        "Brush my teeth every day"
    ]
    let taskNames =
    [
        "Wash car",
        "Read book",
        "drop off food",
        "clean up bedroom",
        "shower",
        "Brush teeth",
        "Turn in homework for history class",
        "Cook dinner for the robinsons",
        "Take medication",
        "go to the gym",
        "comb Ralphy's hair"
    ]
    let chapterNames =
    [
        "The Bahamas!",
        "World domination",
        "Traveling Abroad",
        "My EmOtiOns",
        "Dating. Keep out.",
        "things i don't get",
        "Life is fair",
        "Life is not fair"
    ]
    let entryNames =
    [
        "Best day",
        "worst day",
        "we kissed",
        "helooooooo",
        "big fight at home 2day",
        "omg taylor swift tho",
        "i'm getting fat",
        "time to start working out again..",
        "i'm just happy i'm writing today",
        "what is purpose of LiFeEeEe??"
    ]
    let goalNames =
    [
        "Become an inspiration to others",
        "Master a difficult skill",
        "Become a thought leader in your industry",
        "Get promoted to an executive role at your company",
        "Learn about how to become a millionaire",
        "Go on a trip around the world",
        "Travel to your dream country",
        "Double your personal income",
        "Publish a novel",
        "Take a motorcycle trip",
        "Volunteer at a hospital when it’s safe to do so",
        "Run in a marathon",
        "Get six-pack abs",
        "Achieve zero debt",
        "Invest in the stock market",
        "Drive or buy your dream car",
        "See one of the Seven Wonders of the World",
        "Plan for your retirement",
        "Graduate from college",
        "Learn to fluently speak a foreign language",
        "Meditate daily",
        "Donate to a charity annually",
        "Have a long-term relationship",
        "Climb a mountain",
        "Learn how to surf",
        "Master a musical instrument",
        "Learn how to rock climb",
        "Live in a foreign country",
        "Drink enough water everyday",
        "Give up junk food for a year",
        "Paint a picture",
        "Craft something using pottery skills",
        "Master ballroom dancing",
        "Compose a song",
        "Maintain your ideal body weight",
        "Get paid doing what you’re passionate about",
        "Find your life partner",
        "Learn how to prepare healthy meals",
        "Learn how to lift weights and build muscle",
        "Regularly call your parents",
        "Create multiple income sources",
        "Keep a life journal",
        "Go deep sea fishing",
        "Buy your first house",
        "Build your dream house",
        "Go skydiving",
        "Go hang gliding",
        "Ride in a hot air balloon",
        "Snorkel in the ocean",
        "Climb on a glacier",
        "Go whitewater rafting",
        "See your favorite football team play at their stadium when it’s safe to do so",
        "Go to the Olympics",
        "Get a hole-in-one while golfing",
        "Golf 18 holes under par",
        "Assemble a collection of your favorite books or artwork",
        "Run a six-minute mile",
        "Declutter your home",
        "Appear on a podcast",
        "Read two books every month",
        "Leave a financial inheritance",
        "Trace your ancestry and visit their country of origin",
        "Try a vegan diet for a month",
        "See your favorite musician in concert as often as you can",
        "Create a new family tradition",
        "Maintain a healthy work-life balance",
        "Start an online business",
        "Celebrate your relationship anniversaries",
        "Meet an athlete or celebrity you admire",
        "Practice gratitude everyday",
        "Start a small business",
        "See the ball drop in person on New Year’s Eve when it’s safe to do so",
        "Adopt and care for your dream pet",
        "Give up drinking soda",
        "Witness the Northern Lights",
        "Watch a volcano erupt (from a safe distance!)",
        "Go to Mardi Gras",
        "Develop a good credit score",
        "Learn self-defense",
        "See your doctor and dentist regularly",
        "Always say “yes” to trying new, positive things",
        "Learn yoga",
        "Expand your vocabulary",
        "Participate in a recreational sports league",
        "Grow a thriving garden",
        "Go on a electronics-free camping trip",
        "Write a movie script or TV episode",
        "Learn how to sing",
        "Make your own website",
        "Become a venture capitalist",
        "Sponsor a child in need",
        "Go on a cross-country road trip",
        "Pay off your student loans sooner than later",
        "Learn how to code",
        "Improve your drawing skills",
        "Give up TV for a week",
        "Spend a full day at the spa",
        "Go on a solo vacation",
        "Throw friends a surprise party",
        "Learn how to knit or sew",
        "Find a career that you love.",
        "Find a life partner.",
        "Become an expert or leader in your field.",
        "Go for a walk every day.",
        "Become a better listener.",
        "Buy your first home.",
        "Save X number of dollars for retirement.",
        "Give back to your community in ways that matter to you.",
        "Save enough money to buy something you've always wanted like a boat, cabin, or another item.",
        "Learn how to dance.",
        "Pay off your student loans.",
        "Go on a trip with your best friends.",
        "Lose 10 pounds.",
        "Eat less sugar and junk food.",
        "Get a degree in a subject that matters to you.",
        "Read 1 new book per week.",
        "Learn how to bake.",
        "Get into graduate school.",
        "Help someone else reach one of their dreams.",
        "Write a book.",
        "Go to Switzerland.",
        "Visit all of the American national parks.",
        "Cut your consumption of plastic in half.",
        "Practice gratitude daily.",
        "Improve your public speaking skills.",
        "Learn a foreign language.",
        "Forgive someone who has hurt you.",
        "Become a Leader in your Field",
        "Be Your Own Boss",
        "Find a Career You Love",
        "Get a Degree",
        "Buy a House",
        "Save Enough to Retire",
        "Finding a Life Partner",
        "Fund Your Children’s Education",
        "Become a Millionaire",
        "Learn a Foreign Language",
        "Be a Better Parent",
        "Generate Passive Sources of Income",
        "Invest in Real Estate",
        "Become Debt Free",
        "Declutter You Life",
        "Go on Your Ultimate Vacation",
        "Increase Your Level of Fitness",
        "Live Abroad",
        "Learn a New Skill or Trade",
        "Become a Mentor",
        "Research Your Family Tree",
        "Reach and Maintain Your Ideal Body Weight",
        "Learn to Cook Like a Chef",
        "Turn Your Passion Into a Career",
        "Write a Book",
        "Learn How to Sing",
        "Give a TedTalk",
        "Create an Online Course",
        "Start a Club",
        "Create a Podcast",
        "Start a Blog",
        "Master a Video Game",
        "Be Able to Type Without Looking",
        "Have a Credit Score over 800",
        "Invent Something",
        "Compete in a Fitness Competition",
        "Watch all the Oscar Winning Movies",
        "Conquer a Fear",
        "Learn a New Software Program",
        "Get Straight A’s",
        "To homestead and be self-sufficient. I want to grow my own food and be energy independent.",
        "Build a turnkey, self-sufficient cabin garden and farming homestead community on ~100 acres.",
        "Travel to New Zealand and stay for several weeks.",
        "Own and run self-sufficient “Doomsday” farm with fruit trees, greenhouse, and a huge library.",
        "Have a home far away from city life.",
        "Meet a notable person you admire (author, musician, producer, speaker, leader etc).",
        "Adopt a pet from a shelter",
        "Plant a sustainable community garden.",
        "Learn to scuba dive.",
        "Become fluent in another language.",
        "Snorkel and scuba at The Great Barrier Reef in Australia.",
        "Learn to play an instrument",
        "Go skydiving (or some other high adrenaline activity)",
        "To have a large organic garden, with a year-round greenhouse, that produces most of our food.",
        "To live in a place part of the year where I can surf, windsurf and paddleboard daily.",
        "Build a pole house treehouse retreat in the woods.",
        "Have a family snorkeling vacation in the aqua waters of the Caribbean or Bahamas type places.",
        "Visit Burke’s Garden, Virginia… a gargantuan “sinkhole”.",
        "Be a grandmother/grandfather",
        "Get married to the man/woman of my dreams.",
        "Marry someone who is entrepreneurial like me and wants to create a family business.",
        "Homeschool my children.",
        "Associate with the successful people I respect through the platform of my own accomplishments.",
        "To have a full-time cook to create new healthy recipes for our family and then to publish on a food blog.",
        "Be a mother/father.",
        "To be a dynamically fit, phenomenally successful visionary leader.",
        "Mastering plant-based dieting from all angles of health concern.",
        "Build a retreat center on my dream property.",
        "Learn a form of martial arts.",
        "Lose 20lbs (fill in your desired amount of weight)",
        "Create a health retreat spa and educational program for underprivileged women.",
        "Create a health and retreat program for men to celebrate, engage and recover the power of masculine strength, courage, and chivalry.",
        "Live to be a healthy 100 years old (or more).",
        "Attend a yearly healing retreat that includes health, fitness, gourmet nutrition and spa services.",
        "Host spiritual retreats with interesting and inspiring people.",
        "Owning and operating an experimental garden education, research and development farm.",
        "Create gathering places for like-minded people to create, connect, and collaborate.",
        "Take a workshop class on a skill I want to develop.",
        "To do something that matters. I want to use my gift for words to, in some way, help others unlock their own creative gifts and share their genius with the world.",
        "Be a director, producer, and strategist for podcasters. I want to be able to invest in people who want to create quality audio content and stories.",
        "Be a successful recording artist.",
        "Script and create a fiction podcast that turns into a TV show (TV = Netflix, Amazon Prime, Apple, HBO, etc).",
        "Produce movies for young filmmakers.",
        "Become a bestselling fiction author.",
        "Become a best selling non-fiction author.",
        "Create my own art studio and gallery shop.",
        "Become an accomplished artist.",
        "To be able to make a living from my art, such that I can spend my time and days creating art that I love.",
        "Become an accomplished chef.",
        "Become a successful actor.",
        "Compose a popular movie soundtrack.",
        "Create and own a clothing line.",
        "Create a course that generates recurring passive income, even while I sleep.",
        "Be a successful singer with a large following.",
        "Make enough from writing to support myself.",
        "5-year plan includes starting a tea and honey business (I already have the honey part).",
        "Create a personal brand website.",
        "Invent a successful product.",
        "Create a business website.",
        "Own a horse ranch for breeding, selling, training and enjoying horses.",
        "Start and build a successful eCommerce brand, and expands into retail.",
        "Own a local bookstore coffee shop as a gathering place for interesting people and conversations.",
        "Create local small-town cottage industry businesses to bring jobs and industry back to the USA.",
        "Spend a week with Richard Branson on Necker Island.",
        "Have a location independent business.",
        "Build a brand that sells products globally.",
        "Hire a virtual assistant.",
        "To create a cooking blog and show that gets wildly successful.",
        "Start a podcast that grows quickly, becomes popular and profitable.",
        "Get on the board of future trends think tank.",
        "Hire a team of virtual assistants.",
        "Be a lifestyle entrepreneur able to travel the world while my VA team manages my business.",
        "A media publishing company that provides a platform and a voice to the world for creators and originators, helping them to get their work out into the world.",
        "Build an indoor/outdoor gym business.",
        "Create an entertainment empire which spans several creative mediums and channels.",
        "Speak at a business, tech, or leadership conference.",
        "Host a paid in-person workshop.",
        "Own my own auto racing team.",
        "Invest money, resources, and time in someone else’s startup that aligns with my own business and life values.",
        "Start an educational organization that helps orphanages become financially self-sustaining.",
        "To have ample resources to be able to travel the world.",
        "Become a millionaire.",
        "Be a venture capitalist.",
        "Be in a position financially where I can write full time.",
        "Generate recurring passive income through my investments.",
        "Make loans to a Kiva business each year.",
        "Invest in a life insurance policy",
        "Become—and stay—debt-free.",
        "Be an angel investor.",
        "Become a billionaire.",
        "We're firm believers in the value of putting your goals and visions out into the world... maybe even before you think you're ready. Some people make their own list of 100 life goals, aka 'bucket list'., Others need help and a little inspiration toward identifying their first life goal.",
        "Offer my various arts as a form of caregiving; gifts of love and service to those who need encouragement.",
        "Be a philanthropist.",
        "Start non-profit animal ranch, where rescued and homeless animals can live and be loved and healed surrounded by beauty and peace, and to include walking and hiking trails where people can come and, walk the dogs while getting out in nature and walking themselves.",
        "Create a council of elders that is a think tank for problem solving and philanthropy.",
        "Start an alternative education foundation that helps people bring their dreams to life, with programs for youth, veterans, displaced worker and others struggling to discover and create a life they love.",
        "Empower young people to pursue their dreams.",
        "Support, fund and educate people on how to pursue—and achieve—their dreams.",
        "Volunteer for an organization that helps rehabilitate injured animals.",
        "Travel to, serve and donate to orphanages around the world.",
        "Develop a vision for your life",
        "Establish a positive mindset",
        "Accept what you can’t change",
        "Never set limits on yourself",
        "Cut your path",
        "Embrace change",
        "Manage stress",
        "Live in the moment",
        "Improve your self-confidence",
        "Get up early",
        "Hustle every day",
        "Stop procrastinating",
        "Ask for what you want",
        "Get enough sleep",
        "Exercise regularly",
        "Become a lifelong learner",
        "Keep a journal",
        "Accomplish something first thing",
        "Practice self-care",
        "Improve your interpersonal skills",
        "Learn to be patient",
        "Work smart",
        "Capitalize on change",
        "Capitalize on failure",
        "Become a better listener",
        "Plan and prepare your meals",
        "Have family meals 3 times a week",
        "Improve your time management skills",
        "Find work-life balance",
        "Learn how to express yourself",
        "Master a new skill",
        "Control your temper",
        "Learn to say no",
        "Become more decisive",
        "Improve your body language",
        "Improve one of your weaknesses",
        "Become a better leader",
        "Volunteer for a cause you believe in",
        "Discover your best place to live",
        "Make a “bucket list”",
        "Plan and take a special trip",
        "Read a new book",
        "Take on a new challenge",
        "Expand your network of friends",
        "Find your perfect life partner",
        "Become a better spouse",
        "Grow into a better parent",
        "Remove toxic people from your life",
        "Find a mentor",
        "Become a mentor",
        "Do a nightly gratitude journal for 1 week",
        "Get off screens by 9:00 p.m. everyday for 2 weeks",
        "Do 1 lesson on Justin Guitar per week",
        "Finish one Coursera course within a month",
        "Try one new home cooked meal per week until the end of the year",
        "Give 2% of your monthly income to charity each pay period for two months",
        "Read for 10 hours each month",
        "Water your houseplants every 12 days (not too much!)",
        "Teach yourself one new home repair skill every month",
        "Journal for 15 minutes every morning for 2 weeks",
        "Go to the gym Tuesday, Thursday, and Saturday with no required minimum workout",
        "Only consume 1 alcoholic drink per session for 2 weeks",
        "Meditate for 10 minutes before bed 4 times per week",
        "Wake up 15 minutes earlier to make a real breakfast every workday for 2 weeks",
        "Cut off caffeine at noon every workday for one month",
        "Eat vegetarian on Mondays and Thursdays for 6 weeks",
        "Set a timer to get up and stretch for 2 minutes every hour",
        "Bike to work one day per week for a month",
        "Do a Sunday morning hike every week for a month",
        "Drink only water every Wednesday for 1 month",
        "Complete one continued education online course per month",
        "Research and commit to attending an industry conference within 90 days",
        "Invite one coworker or boss to coffee outside of the workplace per week for 6 weeks",
        "Schedule one informational interview with a grad school counselor by the 1st of next month",
        "Research how to advance your career with more education or training for 5 minutes every day for a week",
        "Get to work 1 minute early every day for a week. Then make it 2 minutes, then 3 – all the way up to the optimal time you want to be at your desk",
        "Reach out to one friend, family member, or acquaintance you admire tomorrow and set a date to discuss how they achieved success",
        "Read 1 amazing book on leadership each month for the next 5 months",
        "Seek out and attend a public speaking or leadership meetup in your town by next week",
        "Visit TED.com and watch one talk by an industry leader per day on your lunch break",
        "Call your high school best friend once per month",
        "Plan a true date night for your partner on the first and third Saturdays of the month",
        "Join a kickball team for a season",
        "Host a game night with friends within the next 20 days",
        "Simply start an interaction with someone you find attractive with zero expectations once per week",
        "Make a meal for someone in the next week",
        "Research 3 options for a couples therapist by the end of the week and have an appointment by the end of the month",
        "Join a spiritual community of some kind for 1 month",
        "Commit to being a better listener for 1 week",
        "Ask someone out on a date, in person, in the next week",
        "Drink only homemade coffee for 10 days",
        "Bring your lunch to work 3 times per week",
        "Any recreational purchase must be added to a Should I Buy This jar/folder/account that can only be acted on after it’s been on the list for 7 days.",
        "Move 5% of your paycheck to a savings account per pay period and assess if you noticed it missing from your wallet at the end of the month",
        "Sign up for a budgeting app like Mint or YNAB, and use it everyday for two weeks. At the end of that time, see if you noticed any changes in your spending habits.",
        "Save on groceries and make a double portion of one of these recipes every week",
        "Open some type of retirement account like  an IRA in the next 14 days.",
        "Create a list of monthly expenses and attempt to reduce it by 10% within the next 10 days",
        "Schedule an appointment with a financial counselor within two weeks",
        "Make a date with yourself and a bottle of wine to honestly look at any credit card debt that’s been lingering for more than six months. Just this could be a huge win for many.",
        "To find what you love to do",
        "Become a business coach",
        "Become location independent by having a laptop lifestyle",
        "Improve relationships with family",
        "To create a foundation to help youth and young adults",
        "To be at my ideal weight",
        "Live a healthy lifestyle",
        "Run in a marathon",
        "Travel to all continents of the world",
        "Become a marketing consultant",
        "Volunteer in a developing country",
        "To speak on stage",
        "Travel around Australia, visiting many of the places in Australia’s Ultimate Bucket List: The Top 100 Places You Should See In Your Lifetime.",
        "To climb the seven peaks",
        "Learn to teach yoga paddling boarding – Yes, it’s a thing.",
        "Graduate from university – on track to finish in 2021",
        "To live with work-life balance",
        "Become a public speaker",
        "Write a personal development book",
        "To read one book a week, currently, I listen to books via audible audiobooks",
        "Fly a plane",
        "Ice skate in New York at Central Park",
        "See the Northern Lights",
        "Go on a cruise to Alaska",
        "To be a giver",
        "To buy a family home",
        "Start a business from scratch, again.",
        "To have zero debt",
        "Learn to play the guitar",
        "Build a six-figure online business",
        "Write a children’s book",
        "Generate a $5,000 online per month",
        "Walk The Camino de Santiago",
        "Teach 1000 people blogging skills",
        "To be a beekeeper",
        "Become a blood donor",
        "Attend an All Blacks game – see the haka live",
        "Go to a rodeo",
        "Learn sign language",
        "Fly a kite",
        "Walk part of the Inca Trail, see Machu Picchu, Peru",
        "Learn backgammon",
        "Learn karate",
        "See a wild koala",
        "Swim with sharks",
        "Learn to play the harmonica",
        "Spend a month being pampered at a health retreat",
        "Learn chess",
        "See the Pyramids of Giza, Cairo, Egypt.",
        "Develop the skill of drawing beautiful pictures like Rose Hill",
        "Learn how to ride a motorbike",
        "Knit 100 blanket squares for charity",
        "Help out at a homeless shelter",
        "Go to the Super Bowl",
        "Start a non-profit organisation",
        "Train a seeing-eye dog",
        "Go to Las Vegas",
        "See a Broadway musical",
        "Sell products on Amazon",
        "Have a personal trainer",
        "Run in a 10k charity race",
        "Cycle on a tandem across the state for charity",
        "Go white water rafting in New Zealand",
        "Attend the country music festival in Tamworth",
        "Write a guest blog post",
        "Jump out of a plane – with a parachute of course. Tandem Jump.",
        "Swim with dolphins",
        "Be an extra in a movie",
        "Learn Reiki",
        "Do a firewalk",
        "Go barramundi fishing",
        "Live debt-free",
        "Have an emergency fund that is to the value of at least a years income.",
        "To go on a bobsled ride in St Moritz",
        "To walk every day for a year 10,000 steps",
        "Stay at a spa retreat 4 times a year",
        "To go on a date night every week with my husband",
        "Fly first class",
        "Be featured in a magazine",
        "To experience van life for a year.",
        "Master 10 yoga poses",
        "Be a role model, be inspiring",
        "Attend a formula one race",
        "Snorkel in the Maladies",
        "Go to the Taj Mahal",
        "Walk over the Zhangjiajie glass bridge, China",
        "Playoff a single golf handicap",
        "Own a classic car",
        "Eat at a 50’s American diner",
        "Walk down the Hollywood Walk of Fame.",
        "Drive a race car around a race track",
        "Attend Bathurst 1000, V8 race",
        "Attend the Summernats in Canberra.",
        "Visit Arnhem land, Australia.",
        "Walk The Great North Walk, Sydney to Newcastle NSW, Australia",
        "Renovate a small home",
        "Grow my own fruit and vegetables",
        "See St. Basil Cathedral, Moscow",
        "Live in alignment with my values",
        "Enjoy life to the fullest",
        "Type 60 words per minute",
        "Study abroad in a foreign country",
        "Get accepted to a college with a Japanese language program",
        "Study abroad in Japan",
        "Graduate college in the top 10 of my class (actually made top 3!)",
        "Save up enough money to buy my prom gown",
        "Get a paid internship",
        "Buy my first car",
        "Get to go to Senior Week at the beach",
        "Redo my bedroom as a high schooler",
        "Pass a Spanish fluency test to get a certification (just barely missed this one)",
        "Volunteer 2-3 hours per week",
        "Master Intuitive Eating",
        "Find a form of enjoyable movement",
        "Feel STRONG (lifting weights or resistance training can help)",
        "Learn how to form a healthy, balanced plate",
        "Create a healthy lifestyle – not a trend or “health kick”",
        "Attend routine health appointments (doctor, dentist, etc.)",
        "Give up dieting",
        "Maintain aerobic fitness (walk, run, jog, cycle, etc.)",
        "Be drug-/tobacco/alcohol-free",
        "Get enough rest every night",
        "Practice gratitude daily",
        "Develop a positive morning routine and night routine",
        "Take time to rest daily",
        "Develop a consistent journaling routine",
        "Surround yourself with uplifting people",
        "Build self-love and body confidence",
        "Set limits on screen time",
        "Get outside once daily (consider taking walks!)",
        "Practice patience with yourself and others",
        "Make a consistent self-care routine",
        "Call an older family member at least once a week (parent, aunt/uncle, grandparent, etc.)",
        "Find a life partner that treats you right",
        "Surround yourself with positive influences",
        "Schedule date nights often (with siblings, friends, significant other, etc.)",
        "Hug someone you love every day",
        "Develop effective communication skills",
        "Become a parent (human or dog 😉 )",
        "Intentionally show someone you love them daily/weekly/monthly",
        "Practice deep conversations",
        "Distance yourself from people who make you feel poorly (boundaries!)",
        "Find a job you’re passionate about",
        "Develop a growth mindset in work",
        "Become your own boss",
        "Get an education/certification",
        "Work from home",
        "Start your own business",
        "Retire at ‘X’ age",
        "Be a good boss/employee",
        "Build strong work relationships",
        "Contribute to a positive work environment",
        "Make ‘X’ amount salary",
        "Add to a retirement fund",
        "Pay off loans/debt",
        "Routinely add to a savings account",
        "Save for a house down payment",
        "Develop a budget plan",
        "Get a financial advisor/learn good finance practices",
        "Save money for travel/recreation",
        "Start a kid’s college fund",
        "Plan your spending monthly",
        "Give at least one compliment a day",
        "Pay it forward whenever possible",
        "Donate to a charity/organization you believe it",
        "Be vocal about your passions",
        "Attend rallies/protests/events that you feel drawn to",
        "Smile at strangers",
        "Be kind to service workers",
        "Volunteer",
        "Share your story to inspire others",
        "Be a positive influence in the lives of children",
        "Read self-help books often",
        "Be honest with yourself",
        "Create an ongoing list of life lessons",
        "Set new goals often (weekly goals, monthly goals)",
        "Learn to see failure as growth",
        "Accept and grow through life changes – do not resist",
        "Develop emotional intelligence",
        "Be resilient",
        "Meet new people to learn from",
        "Listen to motivating podcasts/videos/books",
        "Develop a personal spiritual practice",
        "Practice yoga",
        "Meditate often",
        "Raise your vibration through gratitude",
        "Learn about other religions/spiritual practices",
        "Manifest your future (consider a vision board!)",
        "Take more time away from screens/external stimulation",
        "Learn about your chakras",
        "Build a manifestation list",
        "Spread love to others",
        "life goal ideas81. Own a high-end brand purse/watch/etc.",
        "Live in a house on the water",
        "Take yearly vacations",
        "Drive your dream car",
        "Own a vacation property",
        "Go out to nice dinners to celebrate things in life",
        "Visit all your bucket list travel destinations",
        "Have weekends free from work",
        "Live in a comfortable, cozy, loving home",
        "Have your dream pet",
        "Publish a novel",
        "Run a successful blog",
        "Travel to ‘X’ place (personal dream)",
        "Run a half marathon",
        "Play a live concert",
        "Meet ‘X’ person (Who inspires you? Mine is Glennon Doyle and Abby Wambach for sure!)",
        "Compete in your sport",
        "Start a podcast",
        "Design and sell stationery products",
        "Feel fulfilled in life!",
        "Backpack the Tahoe Rim Trail",
        "Backpack the Pacific Crest Trail",
        "Climb Mt. Whitney",
        "Climb Mt. Fuji",
        "Go on a full-moon hike",
        "Meditate with a monk",
        "See the Aurora Borealis",
        "Experience a Japanese onsen",
        "Visit a Japanese host club",
        "Stay at a ryokan in Japan",
        "Go on a cruise with friends",
        "Become skilled in at least one type of ballroom dance",
        "Run a half-marathon",
        "Do a double Bikram yoga class",
        "Become a skilled swimmer",
        "Participate in a Dressage competition",
        "Do the splits",
        "Do Wheel Pose",
        "Learn ballet",
        "Learn hiphop dance",
        "Become a skilled tennis player",
        "Do 90 days of Bikram yoga",
        "Get six-pack abs (because yes, I’m a little bit vain okay)",
        "Participate in a meditation retreat",
        "Do a Whole30",
        "Adopt a full Paleo lifestyle",
        "Fix my bad neck posture",
        "Meditate an hour a day for 60 days",
        "Practice mindfulness",
        "Live minimally",
        "Practice gratitude daily for a year",
        "Do deep stretching daily for 60 days",
        "Do back bending daily for 90 days",
        "Kick depression and anxiety to the curb",
        "Recognize my own self-worth",
        "Become financially independent",
        "Generate at least 3 streams of income",
        "$10,000 emergency savings fund",
        "$100,000 emergency savings fund",
        "Generate a recurring passive income",
        "Invest in stocks",
        "Purchase a vacation home in Tahoe",
        "Pay off all debt (and remain debt free)",
        "Generate a six-figure income",
        "Purchase a home",
        "Purchase a good car without a loan",
        "Invest in property",
        "Own a home with a library and a secret garden",
        "Vacation with friends every year for 3 years in a row",
        "Go on a wine-tasting girls trip",
        "Shave my head",
        "Dye my hair cotton candy pink",
        "Read 15 non-fiction books in one year",
        "Publish a novel",
        "Live by myself",
        "Decorate and furnish my own place",
        "Feel confident cooking for others",
        "Learn to balance work, a social life, and health",
        "Visit Japan",
        "Visit Ireland",
        "Visit Germany and the city my Grandma was born",
        "Visit Scotland and meet a highlander",
        "Travel to another country solo",
        "Stay in Japan for an extended time",
        "Visit family in Illinois",
        "Visit NYC",
        "Visit Nashville, TN",
        "Visit all of my long-distance friends in one year",
        "Travel to every continent",
        "Visit Austin, TX",
        "Visit Sweden",
        "Visit the Netherlands",
        "Pass the JLPT N3 exam",
        "Pass the JLPT N2 exam",
        "Learn to speak conversational Korean",
        "Learn to speak conversational German",
        "Learn to play piano",
        "Learn to change a tire",
        "Learn how to cook well",
        "Learn to sing",
        "Learn to play tennis",
        "Learn all 10 types of ballroom dance",
        "Build a closer relationship with my brother",
        "Keep in regular contact with all my friends",
        "Have a long-term healthy, loving relationship",
        "Host a women’s coworking event",
        "Host a creative writing seminar",
        "Volunteer at a horse rescue",
        "Volunteer at a women’s shelter",
        "Donate regularly",
        "Pay it forward on a regular basis",
        "Build a financially successful blog",
        "Run two successful blogs",
        "Manage a successful digital ad campaign",
        "Generate 100k monthly uniques on one blog",
        "Build an ethical ecommerce brand",
        "Earn an income from a novel"
    ]
    
    let dreamNames =
    [
        "Inspire others",
        "Master a skill",
        "Get a degree at prestigious university",
        "Get an MBA",
        "Get a Masters degree",
        "Get a Doctorate degree",
        "Become an MD",
        "Get a JD",
        "Become a leader in my industry",
        "Become a business executive",
        "Become a millionaire",
        "Become a billionaire",
        "Travel to all 7 continents",
        "Travel to my dream country",
        "Reach $100k annually",
        "Reach $500k annually",
        "Reach $1M annually",
        "Publish a novel",
        "Run in a marathon",
        "Get six-pack abs",
        "Become debt free",
        "Buy my dream car",
        "See one of the Seven Wonders",
        "See all of the Seven Wonders",
        "Retire comfortably",
        "Graduate college",
        "Learn a new language",
        "Found a charity",
        "Have a long-term relationship",
        "Marry the love of my life",
        "Climb a mountain",
        "Climb Mount Everest",
        "Learn how to surf",
        "Master a musical instrument",
        "Learn how to rock climb",
        "Live in a foreign country",
        "Give up junk food for a year",
        "Become an artist",
        "Learn how to do pottery",
        "Master ballroom dancing",
        "Compose a song",
        "Reach my ideal body type",
        "Get paid to do my passion",
        "Find my life partner",
        "Implement a healthy diet",
        "Learn how to lift weights and build muscle",
        "Generate passive income",
        "Go deep sea fishing",
        "Buy my first house",
        "Build my dream home",
        "Go skydiving",
        "Go hang gliding",
        "Ride in a hot air balloon",
        "Snorkel in the ocean",
        "Climb on a glacier",
        "Go whitewater rafting",
        "See my favorite football team",
        "Go to the Olympics",
        "Get a hole-in-one",
        "Golf 18 holes under par",
        "Assemble a collection of my favorite books or artwork",
        "Run a six-minute mile",
        "Declutter my home",
        "Appear on a podcast",
        "Run my own podcast",
        "Create a youtube channel",
        "Leave a financial inheritance",
        "Trace my ancestry",
        "Try a vegan diet",
        "See my favorite musician in concert",
        "Have a happy family",
        "Create a new family tradition",
        "Maintain a healthy work-life balance",
        "Start an online business",
        "Celebrate my relationship anniversaries",
        "Meet my favorite athlete",
        "Meet my favorite celebrity",
        "Start a small business",
        "See the NYE ball drop",
        "Get my dream pet",
        "Give up drinking soda",
        "Witness the Northern Lights",
        "Watch a volcano erupt",
        "Go on a cruise",
        "Go to Mardi Gras",
        "750 credit score",
        "Learn self-defense",
        "Learn Karate",
        "Learn yoga",
        "Expand my vocabulary",
        "Participate in a recreational sports league",
        "Become professional athlete",
        "Become famous actor/actress",
        "Have children",
        "Grow a thriving garden",
        "Write a movie script or TV episode",
        "Learn how to sing",
        "Sing in a choir",
        "Make my own website",
        "Become a venture capitalist",
        "Sponsor a child in need",
        "Go on a cross-country road trip",
        "Visit every country in the world",
        "Pay off my student loans",
        "Learn how to code",
        "Improve my drawing skills",
        "Go on a solo vacation",
        "Learn how to knit or sew"
    ]
}
